#include <ArduinoJson.h>
#include <map>
#include <string>
#include <cassert>
#include <cstdio>
#include <cstdarg>
#include <vector>
#include <LittleFS.h>
#include "../src/app/alarm_manager.h"
#include "../src/app/action_dispatch.h"
#include "../src/app/action_registry.h"

std::map<std::string, std::string> storage_test_files;
bool storage_test_fail_open = false;
size_t storage_test_write_limit = SIZE_MAX;
FakeLittleFS LittleFS;
static time_t wall_clock = 1704094140;
static unsigned long monotonic_clock = 0;
static bool ready = false;
static bool ota = false;
static uint32_t timezone_revision = 0;
static const char* timezone_name = "UTC0";
static std::vector<std::string> dispatched;
static ActionResult dispatch_result = ACTION_FAILED;
static size_t ota_after_dispatch = SIZE_MAX;
static bool (*last_work_guard)(uint32_t) = nullptr;
static uint32_t last_work_generation = 0;
static bool (*cleanup_work_guard)(uint32_t) = nullptr;
static uint32_t cleanup_work_generation = 0;
static std::vector<std::string> diagnostics;
void log_noop(const char* module, const char* format, ...) {
    if (strcmp(module, "Alarm")) return;
    char message[288];
    va_list arguments;
    va_start(arguments, format);
    const int length = vsnprintf(message, sizeof(message), format, arguments);
    va_end(arguments);
    assert(length >= 0 && length < 256);
    diagnostics.emplace_back(message);
}
static bool has_log(const char* text) {
    for (const auto& message : diagnostics) if (message.find(text) != std::string::npos) return true;
    return false;
}
extern "C" time_t time(time_t* output) noexcept { if (output) *output = wall_clock; return wall_clock; }
extern "C" unsigned long millis() { return monotonic_clock; }
bool time_service_ready() { return ready; }
uint32_t time_service_generation() { return timezone_revision; }
void time_service_get_timezone(char* output, size_t capacity) { strlcpy(output, timezone_name, capacity); }
bool time_service_localtime(time_t epoch, struct tm* result) { return result && gmtime_r(&epoch, result); }
bool time_service_format(time_t epoch, const char* format, const char*, char* output, size_t capacity) {
    struct tm local = {};
    return gmtime_r(&epoch, &local) && strftime(output, capacity, format, &local);
}
time_t time_service_alarm_next(time_t now, uint8_t hour, uint8_t minute, uint8_t weekdays) {
    struct tm local = {};
    gmtime_r(&now, &local);
    const time_t target = now - local.tm_hour * 3600 - local.tm_min * 60 - local.tm_sec + hour * 3600 + minute * 60;
    for (int offset = 0; offset < 15; ++offset) {
        const time_t candidate = target + offset * 86400;
        struct tm date = {};
        gmtime_r(&candidate, &date);
        if (candidate > now && (weekdays & (1U << date.tm_wday))) return candidate;
    }
    return 0;
}
time_t time_service_alarm_candidate(time_t now, uint8_t hour, uint8_t minute, uint8_t weekdays) {
    struct tm local = {};
    gmtime_r(&now, &local);
    const time_t target = now - local.tm_hour * 3600 - local.tm_min * 60 - local.tm_sec + hour * 3600 + minute * 60;
    for (int offset = 0; offset >= -8; --offset) {
        const time_t candidate = target + offset * 86400;
        struct tm date = {};
        gmtime_r(&candidate, &date);
        if (candidate <= now && (weekdays & (1U << date.tm_wday))) return candidate;
    }
    return 0;
}
void storage_publish_usage(bool) {}
bool ota_activity_is_active() { return ota; }
ActionResult action_dispatch(const ButtonAction& action, const char* label, uint32_t) {
    dispatched.emplace_back(std::string(label) + ":" + action.type);
    if (dispatched.size() == ota_after_dispatch) ota = true;
    return dispatch_result;
}
ActionResult action_dispatch_synchronous(const ButtonAction& action, const char* label,
                                         bool (*guard)(uint32_t), uint32_t generation) {
    last_work_guard = guard;
    last_work_generation = generation;
    if (!strcmp(label, "Alarm stop")) {
        cleanup_work_guard = guard;
        cleanup_work_generation = generation;
    }
    return action_dispatch(action, label, 0);
}

static bool save(const char* json) { return alarm_config_save_raw(reinterpret_cast<const uint8_t*>(json), strlen(json)); }
static const char* config = R"({"lateness_minutes":5,"1":{"enabled":true,"hour":7,"minute":30,"weekdays":62,"snooze_minutes":9,"auto_dismiss_minutes":30,"on_ring":[{"type":"screen","target":"info"}],"on_stop":[]}})";

static void test_audio_failure(bool once) {
    storage_test_files.clear();
    ready = true;
    ota = false;
    ota_after_dispatch = SIZE_MAX;
    wall_clock = 1704094140;
    monotonic_clock = 0;
    alarm_manager_init();
    dispatch_result = ACTION_COMPLETE;
    std::string with_cleanup(config);
    if (once) with_cleanup.replace(with_cleanup.find("\"weekdays\":62"), strlen("\"weekdays\":62"), "\"weekdays\":0");
    with_cleanup.replace(with_cleanup.find("\"on_stop\":[]"), strlen("\"on_stop\":[]"),
        "\"on_stop\":[{\"type\":\"screen\",\"target\":\"info\"}]");
    assert(save(with_cleanup.c_str()));
    dispatched.clear();
    wall_clock += 60;
    monotonic_clock += 60000;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING && dispatched.size() == 1);
    assert(!alarm_snapshot().hook_error && (!once || !alarm_snapshot().enabled));
    const auto ring_guard = last_work_guard;
    const auto ring_generation = last_work_generation;
    const auto saved_files = storage_test_files;
    alarm_manager_report_audio_failure(nullptr, ring_generation);
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING);
    alarm_manager_report_audio_failure(ring_guard, ring_generation);
    ota = true;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING);
    ota = false;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_SNOOZED && alarm_snapshot().hook_error);
    assert(alarm_snapshot().snooze_remaining == 9 * 60 && dispatched.size() == 2);
    assert(!ring_guard(ring_generation));
    assert(has_log("Audio playback failed; automatically snoozed"));
    alarm_manager_report_audio_failure(ring_guard, ring_generation);
    monotonic_clock += 9 * 60000 - 1;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_SNOOZED && dispatched.size() == 2);
    ++monotonic_clock;
    wall_clock += 9 * 60;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING && dispatched.size() == 3);
    assert(storage_test_files == saved_files);
    assert(cleanup_work_guard(cleanup_work_generation));
    alarm_manager_report_audio_failure(cleanup_work_guard, cleanup_work_generation);
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING);
    alarm_manager_report_audio_failure(ring_guard, ring_generation);
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING);
    alarm_manager_report_audio_failure(last_work_guard, last_work_generation);
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_SNOOZED && dispatched.size() == 4);
    assert(alarm_command_submit("cancel"));
    alarm_manager_loop();
    monotonic_clock += 9 * 60000;
    wall_clock += 9 * 60;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_IDLE && dispatched.size() == 4);
    alarm_manager_init();
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_IDLE && dispatched.size() == 4);
    dispatch_result = ACTION_FAILED;
}

static void test_once() {
    std::string once(config);
    once.replace(once.find("\"weekdays\":62"), strlen("\"weekdays\":62"), "\"weekdays\":0");
    storage_test_files.clear();
    ready = true;
    wall_clock = 1704094140;
    monotonic_clock = 0;
    alarm_manager_init();
    assert(save(once.c_str()));
    const time_t target = wall_clock + 60;
    assert(alarm_snapshot().once_epoch == target);
    wall_clock += 30;
    alarm_manager_init();
    assert(alarm_snapshot().once_epoch == target);
    assert(save(once.c_str()));
    assert(alarm_snapshot().once_epoch == target);
    ++timezone_revision;
    alarm_manager_loop();
    assert(alarm_snapshot().once_epoch == target);
    JsonDocument status;
    alarm_status_to_json(status.to<JsonObject>());
    assert(status["enabled"] == true && status["once_epoch"].as<int64_t>() == target);
    assert(!strcmp(status["once_local"].as<const char*>(), "2024-01-01 07:30"));
    wall_clock += 30;
    dispatched.clear();
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING && !alarm_snapshot().enabled);
    assert(alarm_snapshot().once_epoch == 0 && dispatched.size() == 1);
    assert(last_work_guard(last_work_generation));
    assert(alarm_command_submit("snooze"));
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_SNOOZED && !last_work_guard(last_work_generation));
    monotonic_clock += 9 * 60000;
    wall_clock += 9 * 60;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING && dispatched.size() == 2);
    monotonic_clock += 30 * 60000;
    wall_clock += 30 * 60;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_IDLE);
    alarm_manager_init();
    wall_clock += 86400;
    alarm_manager_loop();
    assert(!alarm_snapshot().enabled && dispatched.size() == 2);
    assert(save(once.c_str()));
    assert(alarm_snapshot().enabled && alarm_snapshot().once_epoch > wall_clock);
    storage_test_files.clear();
    wall_clock = 1704094140;
    alarm_manager_init();
    assert(save(once.c_str()));
    storage_test_write_limit = 8;
    wall_clock += 60;
    dispatched.clear();
    alarm_manager_loop();
    assert(!alarm_snapshot().enabled && alarm_snapshot().storage_error);
    assert(alarm_snapshot().state == ALARM_RINGING && dispatched.size() == 1);
    storage_test_write_limit = SIZE_MAX;
    ++wall_clock;
    alarm_manager_loop();
    assert(!alarm_snapshot().enabled && alarm_snapshot().state == ALARM_RINGING && dispatched.size() == 1);
    storage_test_files.clear();
    wall_clock = 1704094140;
    alarm_manager_init();
    assert(save(once.c_str()));
    wall_clock += 361;
    dispatched.clear();
    alarm_manager_loop();
    assert(!alarm_snapshot().enabled && alarm_snapshot().state == ALARM_IDLE && dispatched.empty());
    alarm_manager_init();
    assert(!alarm_snapshot().enabled);
    ButtonAction invalid = {};
    strlcpy(invalid.type, "alarm", sizeof(invalid.type));
    strlcpy(invalid.payload.alarm.alarm_command, "adjust_minutes", sizeof(invalid.payload.alarm.alarm_command));
    strlcpy(invalid.payload.alarm.alarm_value, "1.5", sizeof(invalid.payload.alarm.alarm_value));
    invalid.payload.alarm.alarm_id = 1;
    assert(action_type_find("alarm")->dispatch(invalid, "test", 0) == ACTION_FAILED);
    assert(alarm_snapshot().command_error);
    storage_test_files.clear();
    wall_clock = 1704094140;
    alarm_manager_init();
    assert(save(once.c_str()));
    wall_clock += 61;
    alarm_manager_init();
    dispatched.clear();
    alarm_manager_loop();
    assert(!alarm_snapshot().enabled && dispatched.size() == 1);
    storage_test_files.clear();
    ready = false;
    wall_clock = 1704094140;
    alarm_manager_init();
    assert(save(once.c_str()));
    assert(alarm_snapshot().once_epoch == 0);
    wall_clock += 120;
    ready = true;
    alarm_manager_loop();
    assert(alarm_snapshot().enabled && alarm_snapshot().once_epoch == 1704180600);
    storage_test_files.clear();
    ready = true;
    wall_clock = 1704094140;
    alarm_manager_init();
    assert(save(once.c_str()));
    ota = true;
    wall_clock += 60;
    dispatched.clear();
    alarm_manager_loop();
    assert(alarm_snapshot().deferred && dispatched.empty());
    ota = false;
    wall_clock += 300;
    alarm_manager_loop();
    assert(!alarm_snapshot().enabled && alarm_snapshot().state == ALARM_RINGING && dispatched.size() == 1);
    storage_test_files.clear();
    ready = false;
    ota = false;
    wall_clock = 1704094140;
    monotonic_clock = 0;
    dispatched.clear();
    diagnostics.clear();
}

static uint64_t persisted_generation() {
    uint64_t newest = 0;
    for (const auto& file : storage_test_files) {
        JsonDocument document;
        if (!deserializeJson(document, file.second))
            newest = std::max(newest, document["generation"].as<uint64_t>());
    }
    return newest;
}

static void test_recovery() {
    const time_t start = 1704094140;
    std::string recovery_config(config);
    recovery_config.replace(recovery_config.find("\"lateness_minutes\":5"), strlen("\"lateness_minutes\":5"), "\"lateness_minutes\":360");
    auto prepare = [&] {
        storage_test_files.clear();
        storage_test_fail_open = false;
        storage_test_write_limit = SIZE_MAX;
        ready = true;
        ota = false;
        timezone_name = "UTC0";
        wall_clock = start;
        monotonic_clock = 0;
        dispatched.clear();
        alarm_manager_init();
        assert(alarm_snapshot().lateness_minutes == 360);
        assert(save(recovery_config.c_str()));
    };
    auto reboot = [&](time_t elapsed, bool synchronized) {
        wall_clock = start + elapsed;
        monotonic_clock = 0;
        ready = synchronized;
        alarm_manager_init();
        alarm_manager_loop();
    };
    prepare();
    std::string legacy(recovery_config);
    legacy.erase(1, legacy.find("\"1\"") - 1);
    assert(!save(legacy.c_str()));
    std::string invalid(recovery_config);
    invalid.replace(invalid.find("360"), 3, "10081");
    assert(!save(invalid.c_str()));
    invalid = recovery_config;
    invalid.replace(invalid.find("360"), 3, "1.5");
    assert(!save(invalid.c_str()));
    reboot(60 + 21600, false);
    assert(dispatched.empty());
    ready = true;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING && dispatched.size() == 1);
    assert(alarm_command_submit("cancel"));
    alarm_manager_loop();
    reboot(60 + 21600, true);
    assert(alarm_snapshot().state == ALARM_IDLE && dispatched.size() == 1);
    wall_clock = start;
    alarm_manager_loop();
    wall_clock += 600;
    alarm_manager_loop();
    assert(dispatched.size() == 1);

    prepare();
    reboot(60 + 21601, true);
    assert(alarm_snapshot().state == ALARM_IDLE && dispatched.empty());
    prepare();
    reboot(600, false);
    wall_clock = start + 60 + 21601;
    ready = true;
    alarm_manager_loop();
    assert(dispatched.empty());
    prepare();
    reboot(21 * 86400 + 600, true);
    assert(dispatched.size() == 1);
    alarm_manager_loop();
    assert(dispatched.size() == 1);

    prepare();
    wall_clock += 600;
    assert(alarm_command_submit("disable", 1));
    alarm_manager_loop();
    assert(alarm_command_submit("enable", 1));
    alarm_manager_loop();
    JsonDocument edited;
    alarm_config_to_json(edited.to<JsonObject>());
    std::string payload;
    serializeJson(edited, payload);
    assert(save(payload.c_str()));
    reboot(601, true);
    assert(dispatched.empty());

    prepare();
    ready = false;
    assert(alarm_command_submit("adjust_minutes", 1, 1));
    alarm_manager_loop();
    alarm_config_to_json(edited.to<JsonObject>());
    payload.clear();
    serializeJson(edited, payload);
    assert(save(payload.c_str()));
    reboot(600, false);
    ready = true;
    alarm_manager_loop();
    reboot(601, true);
    assert(dispatched.empty());

    prepare();
    timezone_name = "CET-1";
    reboot(600, true);
    assert(dispatched.empty());
    reboot(601, true);
    assert(dispatched.empty());

    prepare();
    reboot(600, false);
    storage_test_fail_open = true;
    ready = true;
    alarm_manager_loop();
    assert(dispatched.size() == 1 && alarm_snapshot().storage_error && alarm_snapshot().save_pending);
    alarm_manager_loop();
    assert(dispatched.size() == 1);
    storage_test_fail_open = false;
    monotonic_clock += 10000;
    alarm_manager_loop();
    assert(!alarm_snapshot().storage_error && !alarm_snapshot().save_pending);
    reboot(601, true);
    assert(dispatched.size() == 1);

    prepare();
    reboot(600, false);
    storage_test_fail_open = true;
    ready = true;
    alarm_manager_loop();
    assert(dispatched.size() == 1);
    storage_test_fail_open = false;
    reboot(601, true);
    assert(dispatched.size() == 2);

    prepare();
    std::string on_time(recovery_config);
    on_time.replace(on_time.find("360"), 3, "0");
    assert(save(on_time.c_str()));
    reboot(61, true);
    assert(dispatched.empty());
    prepare();
    assert(save(on_time.c_str()));
    reboot(60, true);
    assert(dispatched.size() == 1);

    prepare();
    wall_clock += 600;
    std::string wider(recovery_config);
    wider.replace(wider.find("360"), 3, "720");
    assert(save(wider.c_str()));
    alarm_manager_loop();
    assert(dispatched.size() == 1 && alarm_snapshot().lateness_minutes == 720);
    assert(save(recovery_config.c_str()));
    assert(alarm_snapshot().state == ALARM_RINGING);

    prepare();
    std::string once(recovery_config);
    once.replace(once.find("\"weekdays\":62"), strlen("\"weekdays\":62"), "\"weekdays\":0");
    assert(save(once.c_str()));
    reboot(60 + 21600, false);
    ready = true;
    storage_test_fail_open = true;
    alarm_manager_loop();
    assert(dispatched.size() == 1 && !alarm_snapshot().enabled && alarm_snapshot().storage_error);
    assert(alarm_snapshot().once_epoch == 0 && alarm_snapshot().state == ALARM_RINGING);
    storage_test_fail_open = false;
    monotonic_clock += 10000;
    alarm_manager_loop();
    assert(!alarm_snapshot().storage_error);
    reboot(60 + 21600, true);
    assert(dispatched.size() == 1 && !alarm_snapshot().enabled);
    prepare();
    assert(save(once.c_str()));
    reboot(60 + 21601, true);
    assert(dispatched.empty() && !alarm_snapshot().enabled);

    prepare();
    ready = false;
    assert(save(once.c_str()));
    ready = true;
    storage_test_fail_open = true;
    alarm_manager_loop();
    assert(alarm_snapshot().once_epoch == start + 60);
    wall_clock = start + 60;
    alarm_manager_loop();
    assert(dispatched.size() == 1 && !alarm_snapshot().enabled && alarm_snapshot().storage_error);
    storage_test_fail_open = false;
    monotonic_clock += 10000;
    alarm_manager_loop();
    assert(!alarm_snapshot().storage_error);

    prepare();
    std::string long_window(recovery_config);
    long_window.replace(long_window.find("360"), 3, "10080");
    long_window.replace(long_window.find("\"weekdays\":62"), strlen("\"weekdays\":62"), "\"weekdays\":2");
    assert(save(long_window.c_str()));
    reboot(2 * 86400 + 600, true);
    assert(dispatched.size() == 1);

    storage_test_files.clear();
    dispatched.clear();
    diagnostics.clear();
    ready = false;
    wall_clock = start;
    monotonic_clock = 0;
}

static void test_settings_debounce() {
    storage_test_files.clear();
    ready = true;
    ota = false;
    wall_clock = 1704094140;
    monotonic_clock = 0;
    alarm_manager_init();
    assert(save(config));
    const auto initial_files = storage_test_files;
    const uint64_t initial_generation = persisted_generation();
    assert(alarm_command_submit("adjust_minutes", 1, 1));
    alarm_manager_loop();
    assert(alarm_snapshot().minute == 31 && alarm_snapshot().save_pending);
    assert(alarm_snapshot().pending_commands == 0 && storage_test_files == initial_files);
    JsonDocument status;
    alarm_status_to_json(status.to<JsonObject>());
    assert(status["save_state"] == "pending" && status["completed_commands"] == 1);
    monotonic_clock = 5000;
    assert(alarm_command_submit("adjust_minutes", 1, 1));
    alarm_manager_loop();
    assert(alarm_snapshot().minute == 32 && storage_test_files == initial_files);
    monotonic_clock = 10000;
    assert(alarm_command_submit("adjust_minutes", 1, 0));
    alarm_manager_loop();
    assert(storage_test_files == initial_files);
    monotonic_clock = 14999;
    alarm_manager_loop();
    assert(storage_test_files == initial_files);
    monotonic_clock = 15000;
    alarm_manager_loop();
    assert(persisted_generation() == initial_generation + 1 && !alarm_snapshot().save_pending);
    alarm_status_to_json(status.to<JsonObject>());
    assert(status["save_state"] == "saved");
    assert(alarm_command_submit("adjust_minutes", 1, 1));
    alarm_manager_loop();
    assert(alarm_snapshot().minute == 33);
    alarm_manager_init();
    assert(alarm_snapshot().minute == 32 && !alarm_snapshot().save_pending);
    assert(alarm_command_submit("adjust_minutes", 1, 1));
    alarm_manager_loop();
    JsonDocument live;
    alarm_config_to_json(live.to<JsonObject>());
    std::string payload;
    serializeJson(live, payload);
    const uint64_t before_explicit = persisted_generation();
    assert(save(payload.c_str()));
    assert(persisted_generation() == before_explicit + 1 && !alarm_snapshot().save_pending);
    alarm_manager_init();
    assert(alarm_snapshot().minute == 33);
    assert(alarm_command_submit("adjust_minutes", 1, 1));
    alarm_manager_loop();
    assert(alarm_snapshot().minute == 34);
    storage_test_write_limit = 8;
    monotonic_clock += 10000;
    alarm_manager_loop();
    assert(alarm_snapshot().minute == 34 && alarm_snapshot().save_pending && alarm_snapshot().save_failed);
    alarm_status_to_json(status.to<JsonObject>());
    assert(status["save_state"] == "failed" && status["command_error"] == true);
    assert(strlen(status["command_message"].as<const char*>()) > 0);
    const auto failed_files = storage_test_files;
    storage_test_write_limit = SIZE_MAX;
    monotonic_clock += 9999;
    alarm_manager_loop();
    assert(storage_test_files == failed_files);
    ++monotonic_clock;
    alarm_manager_loop();
    assert(!alarm_snapshot().save_pending && !alarm_snapshot().command_error);
    alarm_status_to_json(status.to<JsonObject>());
    assert(status["save_state"] == "saved");
    alarm_manager_init();
    assert(alarm_snapshot().minute == 34);
    assert(alarm_command_submit("weekday_toggle", 1, 0, 0));
    alarm_manager_loop();
    const auto before_ota = storage_test_files;
    ota = true;
    monotonic_clock += 10000;
    alarm_manager_loop();
    assert(storage_test_files == before_ota && alarm_snapshot().save_pending);
    ota = false;
    alarm_manager_loop();
    assert(!alarm_snapshot().save_pending && storage_test_files != before_ota);
    alarm_manager_init();
    assert(alarm_snapshot().weekdays == 63);
    for (bool once : {false, true}) {
        storage_test_files.clear();
        monotonic_clock = 0;
        wall_clock = 1704094195;
        alarm_manager_init();
        std::string schedule(config);
        if (once) schedule.replace(schedule.find("\"weekdays\":62"), strlen("\"weekdays\":62"), "\"weekdays\":0");
        assert(save(schedule.c_str()));
        const uint64_t before_ring = persisted_generation();
        assert(alarm_command_submit("set_time", 1, 451));
        alarm_manager_loop();
        assert(alarm_command_submit("set_time", 1, 450));
        alarm_manager_loop();
        assert(alarm_snapshot().save_pending && persisted_generation() == before_ring);
        wall_clock += 5;
        monotonic_clock = 5000;
        dispatched.clear();
        alarm_manager_loop();
        assert(alarm_snapshot().state == ALARM_RINGING && dispatched.size() == 1);
        assert(persisted_generation() == before_ring + 1 && !alarm_snapshot().save_pending);
        if (once) assert(!alarm_snapshot().enabled);
        const auto ring_files = storage_test_files;
        monotonic_clock = 15000;
        alarm_manager_loop();
        assert(storage_test_files == ring_files && alarm_snapshot().state == ALARM_RINGING);
        storage_test_write_limit = 8;
        assert(alarm_command_submit("adjust_minutes", 1, 1));
        alarm_manager_loop();
        assert(alarm_snapshot().state == ALARM_IDLE && alarm_snapshot().minute == 31);
        assert(alarm_snapshot().save_pending && !alarm_snapshot().command_error);
        monotonic_clock += 10000;
        alarm_manager_loop();
        assert(alarm_snapshot().state == ALARM_IDLE && alarm_snapshot().minute == 31 && alarm_snapshot().save_failed);
        storage_test_write_limit = SIZE_MAX;
    }
    storage_test_files.clear();
    ready = false;
    ota = false;
    wall_clock = 1704094140;
    monotonic_clock = 0;
    dispatched.clear();
    diagnostics.clear();
}

static void test_section_saves() {
    storage_test_files.clear();
    ready = true;
    ota = false;
    alarm_manager_init();
    assert(save(config));
    const char* schedule = R"({"enabled":true,"hour":8,"minute":15,"weekdays":127})";
    assert(alarm_config_save_section_raw(reinterpret_cast<const uint8_t*>(schedule), strlen(schedule), AlarmConfigSection::Schedule));
    JsonDocument stored;
    alarm_config_to_json(stored.to<JsonObject>());
    assert(stored["1"]["hour"] == 8 && stored["1"]["minute"] == 15);
    assert(stored["1"]["snooze_minutes"] == 9 && stored["lateness_minutes"] == 5);
    assert(stored["1"]["on_ring"].size() == 1);
    assert(alarm_command_submit("set_time", 1, 555));
    alarm_manager_loop();
    const char* behavior = R"({"lateness_minutes":60,"snooze_minutes":12,"auto_dismiss_minutes":45,"on_ring":[],"on_stop":[]})";
    assert(alarm_config_save_section_raw(reinterpret_cast<const uint8_t*>(behavior), strlen(behavior), AlarmConfigSection::Behavior));
    alarm_config_to_json(stored.to<JsonObject>());
    assert(stored["1"]["hour"] == 9 && stored["1"]["minute"] == 15);
    assert(stored["1"]["weekdays"] == 127 && stored["1"]["enabled"] == true);
    assert(stored["1"]["snooze_minutes"] == 12 && stored["lateness_minutes"] == 60);
    const char* invalid = R"({"enabled":true,"hour":8,"minute":15,"snooze_minutes":1})";
    assert(!alarm_config_save_section_raw(reinterpret_cast<const uint8_t*>(invalid), strlen(invalid), AlarmConfigSection::Schedule));
    storage_test_files.clear();
}

int main() {
    test_section_saves();
    test_audio_failure(false);
    test_audio_failure(true);
    test_recovery();
    test_settings_debounce();
    test_once();
    alarm_manager_init();
    assert(!alarm_snapshot().enabled);
    assert(!alarm_command_submit("adjust_minutes", 0, 1));
    assert(!alarm_command_submit("set_time", 1, 1440));
    assert(!alarm_command_submit("weekday_toggle", 1, 0, 7));
    assert(!alarm_command_submit("unknown", 1));
    assert(alarm_command_submit("set_time", 1, 1439));
    alarm_manager_loop();
    assert(alarm_snapshot().hour == 23 && alarm_snapshot().minute == 59);
    assert(alarm_command_submit("adjust_minutes", 1, 1));
    alarm_manager_loop();
    assert(alarm_snapshot().hour == 0 && alarm_snapshot().minute == 0);
    assert(alarm_command_submit("adjust_minutes", 1, -1));
    alarm_manager_loop();
    assert(alarm_snapshot().hour == 23 && alarm_snapshot().minute == 59);
    storage_test_write_limit = 8;
    assert(alarm_command_submit("set_time", 1, 60));
    alarm_manager_loop();
    assert(alarm_snapshot().hour == 1 && alarm_snapshot().minute == 0);
    assert(alarm_snapshot().save_pending && !alarm_snapshot().command_error);
    monotonic_clock += 10000;
    alarm_manager_loop();
    storage_test_write_limit = SIZE_MAX;
    assert(alarm_snapshot().command_error && alarm_snapshot().completed_commands == 4);
    assert(alarm_command_submit("weekday_enable", 1, 0, 1));
    assert(alarm_command_submit("weekday_toggle", 1, 0, 6));
    assert(alarm_command_submit("weekday_disable", 1, 0, 1));
    assert(alarm_command_submit("enable", 1));
    assert(!alarm_command_submit("toggle", 1));
    assert(alarm_snapshot().pending_commands == 4);
    alarm_manager_loop();
    assert(alarm_snapshot().weekdays == 2 && alarm_snapshot().pending_commands == 3);
    alarm_manager_loop();
    assert(alarm_snapshot().weekdays == 66);
    alarm_manager_loop();
    assert(alarm_snapshot().weekdays == 64);
    alarm_manager_loop();
    assert(alarm_snapshot().enabled);
    monotonic_clock += 10000;
    alarm_manager_loop();
    assert(!alarm_snapshot().command_error && !alarm_snapshot().save_pending);
    const auto saved_files = storage_test_files;
    assert(alarm_command_submit("enable", 1));
    alarm_manager_loop();
    assert(saved_files == storage_test_files);
    for (int tick = 0; tick < 100; ++tick) alarm_manager_loop();
    assert(saved_files == storage_test_files);
    alarm_manager_init();
    assert(alarm_snapshot().enabled && alarm_snapshot().weekdays == 64);
    assert(alarm_command_submit("disable", 1));
    alarm_manager_loop();
    assert(!alarm_snapshot().enabled && alarm_snapshot().weekdays == 64);
    assert(alarm_command_submit("toggle", 1));
    alarm_manager_loop();
    assert(alarm_snapshot().enabled);
    assert(alarm_command_submit("adjust_minutes", 1, INT32_MAX));
    alarm_manager_loop();
    assert(alarm_snapshot().hour * 60 + alarm_snapshot().minute == (60LL + INT32_MAX) % 1440);
    storage_test_files.clear();
    alarm_manager_init();
    assert(save(config));
    assert(alarm_snapshot().enabled && alarm_snapshot().minute == 30);
    alarm_manager_init();
    assert(alarm_snapshot().enabled && alarm_snapshot().minute == 30);
    storage_test_write_limit = 8;
    std::string changed(config);
    changed.replace(changed.find("30,"), 3, "31,");
    assert(!save(changed.c_str()));
    assert(alarm_snapshot().minute == 30);
    alarm_manager_init();
    assert(alarm_snapshot().enabled && alarm_snapshot().minute == 30);
    storage_test_write_limit = SIZE_MAX;
    assert(save(changed.c_str()));
    alarm_manager_init();
    assert(alarm_snapshot().minute == 31);
    assert(!save(R"({"1":{"enabled":true,"hour":7,"minute":30,"weekdays":62,"snooze_minutes":9,"auto_dismiss_minutes":30,"on_ring":[{"type":"delay","duration_ms":10}],"on_stop":[]}})"));
    assert(!save(R"({"1":{"enabled":true,"hour":7,"minute":30,"weekdays":62,"snooze_minutes":9,"auto_dismiss_minutes":30,"on_ring":[{"type":"key","key_sequence":"A"}],"on_stop":[]}})"));
    assert(!save("{}"));
    assert(!alarm_command_submit("cancel", 2));
    assert(alarm_command_submit("cancel"));
    storage_test_files["/config/alarm_b.json"] = "corrupt";
    alarm_manager_init();
    assert(alarm_snapshot().minute == 30);
    storage_test_files["/config/alarm_a.json"] = "corrupt";
    alarm_manager_init();
    assert(!alarm_snapshot().enabled && alarm_snapshot().storage_error);
    storage_test_files.clear();
    ready = true;
    wall_clock = 1704094140;
    alarm_manager_init();
    std::string hooked(config);
    hooked.replace(hooked.find("\"on_stop\":[]"), strlen("\"on_stop\":[]"), "\"on_stop\":[{\"type\":\"screen\",\"target\":\"info\"}]");
    hooked.replace(hooked.find("\"on_ring\":["), strlen("\"on_ring\":["), "\"on_ring\":[{\"type\":\"screen\",\"target\":\"info\"},");
    assert(save(hooked.c_str()));
    wall_clock += 60;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING);
    assert(dispatched.size() == 2 && alarm_snapshot().hook_error);
    assert(alarm_snapshot().next_epoch > wall_clock);
    assert(alarm_command_submit("adjust_minutes", 1, 0));
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING && dispatched.size() == 2);
    assert(save(hooked.c_str()));
    assert(alarm_snapshot().state == ALARM_RINGING && dispatched.size() == 2);
    std::string edited(hooked);
    edited.replace(edited.find("30,"), 3, "31,");
    storage_test_write_limit = 8;
    assert(!save(edited.c_str()));
    assert(alarm_snapshot().state == ALARM_RINGING && dispatched.size() == 2);
    storage_test_write_limit = SIZE_MAX;
    assert(alarm_command_submit("snooze"));
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_SNOOZED && dispatched.size() == 3);
    assert(alarm_snapshot().snooze_remaining == 540);
    assert(alarm_command_submit("cancel"));
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_IDLE && dispatched.size() == 3);
    wall_clock += 86400;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING && dispatched.size() == 5);
    assert(alarm_command_submit("adjust_minutes", 1, 1));
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_IDLE && dispatched.size() == 6);
    assert(dispatched.back() == "Alarm stop:screen");
    const uint32_t cleanup_generation = last_work_generation;
    assert(last_work_guard(cleanup_generation));
    assert(alarm_command_submit("cancel"));
    alarm_manager_loop();
    assert(last_work_guard(cleanup_generation) && dispatched.size() == 6);
    std::string oversized(hooked);
    oversized.replace(oversized.find("\"info\""), 6, "\"" + std::string(512, 'a') + "\"");
    assert(!save(oversized.c_str()));
    wall_clock += 60;
    ota_after_dispatch = dispatched.size() + 1;
    alarm_manager_loop();
    assert(ota && dispatched.size() == 7 && alarm_snapshot().deferred);
    alarm_manager_loop();
    assert(dispatched.size() == 7);
    ota = false;
    ota_after_dispatch = SIZE_MAX;
    alarm_manager_loop();
    assert(dispatched.size() == 8 && !alarm_snapshot().deferred);
    assert(alarm_command_submit("cancel"));
    ota = true;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_IDLE && dispatched.size() == 8);
    ota = false;
    alarm_manager_loop();
    assert(dispatched.size() == 9 && dispatched.back() == "Alarm stop:screen");
    wall_clock += 86400;
    ota_after_dispatch = dispatched.size() + 1;
    alarm_manager_loop();
    assert(ota && dispatched.size() == 10);
    assert(alarm_command_submit("cancel"));
    alarm_manager_loop();
    ota = false;
    ota_after_dispatch = SIZE_MAX;
    alarm_manager_loop();
    assert(dispatched.size() == 11 && alarm_snapshot().state == ALARM_IDLE);
    wall_clock += 86400;
    ota_after_dispatch = dispatched.size() + 1;
    alarm_manager_loop();
    wall_clock += 301;
    ota = false;
    ota_after_dispatch = SIZE_MAX;
    alarm_manager_loop();
    assert(dispatched.size() == 13 && alarm_snapshot().state == ALARM_IDLE);
    storage_test_files.clear();
    wall_clock = 1704094140;
    monotonic_clock = 0;
    alarm_manager_init();
    assert(save(hooked.c_str()));
    dispatched.clear();
    storage_test_write_limit = 8;
    wall_clock += 60;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING && alarm_snapshot().storage_error);
    assert(dispatched.size() == 2);
    const auto failed_history_files = storage_test_files;
    for (int tick = 0; tick < 3; ++tick) alarm_manager_loop();
    assert(dispatched.size() == 2 && storage_test_files == failed_history_files);
    storage_test_write_limit = SIZE_MAX;
    ++timezone_revision;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_IDLE && dispatched.size() == 3);
    assert(dispatched.back() == "Alarm stop:screen");
    storage_test_files.clear();
    wall_clock = 1704094140;
    monotonic_clock = 0;
    ready = false;
    alarm_manager_init();
    assert(save(config));
    diagnostics.clear();
    alarm_manager_loop();
    assert(diagnostics.size() == 1 && has_log("blocked=waiting-ntp"));
    for (int tick = 0; tick < 100; ++tick) alarm_manager_loop();
    assert(diagnostics.size() == 1);
    wall_clock += 60;
    monotonic_clock += 60000;
    alarm_manager_loop();
    assert(diagnostics.size() == 2);
    ready = true;
    alarm_manager_loop();
    assert(has_log("Time readiness=1") && has_log("blocked=rearmed"));
    wall_clock += 60;
    monotonic_clock += 60000;
    alarm_manager_loop();
    assert(has_log("blocked=before-armed-minute"));
    wall_clock += 86400;
    monotonic_clock += 86400000;
    alarm_manager_loop();
    assert(alarm_snapshot().state == ALARM_RINGING);
    assert(has_log("Ring started: reason=schedule"));
    assert(has_log("Alarm ring hook 1/1: dispatch type=screen"));
    assert(has_log("Alarm ring hook 1/1: failed result="));
    const size_t log_count = diagnostics.size();
    for (int tick = 0; tick < 100; ++tick) alarm_manager_loop();
    assert(diagnostics.size() == log_count);
    std::puts("alarm manager persistence: PASS");
}