#pragma once

// ============================================================================
// Custom Display Fonts — extern declarations for generated LVGL fonts
// ============================================================================
// These fonts are generated by tools/generate-fonts.sh from TTF source files.
// Gated by HAS_CUSTOM_FONTS (requires HAS_DISPLAY).
//
// To add a new font:
//   1. Add entry to FONTS array in tools/generate-fonts.sh
//   2. Run ./tools/generate-fonts.sh
//   3. Add extern declaration below
//   4. Add entry to pad_custom_font_lookup() in pad_layout.h
//   5. Rebuild firmware

#include "board_config.h"

#if HAS_CUSTOM_FONTS

#include <lvgl.h>

// Font family identifiers (used in LabelStyle.font_family)
#define FONT_FAMILY_DEFAULT   0  // Montserrat (LVGL built-in)
#define FONT_FAMILY_DSEG7     1  // 7-segment LCD display
#define FONT_FAMILY_BEBAS     2  // Bold condensed display
#define FONT_FAMILY_DOTO      3  // Dot-matrix display
#define FONT_FAMILY_COUNT     4  // Total number of families (including default)

// DSEG7 Classic Bold — 7-segment LCD display (SIL OFL 1.1)
// Sizes: 12, 14, 18, 24, 32, 36, 48 (matches Montserrat)
LV_FONT_DECLARE(font_dseg7_12);
LV_FONT_DECLARE(font_dseg7_14);
LV_FONT_DECLARE(font_dseg7_18);
LV_FONT_DECLARE(font_dseg7_24);
LV_FONT_DECLARE(font_dseg7_32);
LV_FONT_DECLARE(font_dseg7_36);
LV_FONT_DECLARE(font_dseg7_48);

// Bebas Neue — Bold condensed display (SIL OFL 1.1)
// Sizes: 12, 14, 18, 24, 32, 36, 48 (matches Montserrat)
LV_FONT_DECLARE(font_bebas_12);
LV_FONT_DECLARE(font_bebas_14);
LV_FONT_DECLARE(font_bebas_18);
LV_FONT_DECLARE(font_bebas_24);
LV_FONT_DECLARE(font_bebas_32);
LV_FONT_DECLARE(font_bebas_36);
LV_FONT_DECLARE(font_bebas_48);

// Doto — Dot-matrix display, Black 900 weight (SIL OFL 1.1)
// Sizes: 12, 14, 18, 24, 32, 36, 48 (matches Montserrat)
LV_FONT_DECLARE(font_doto_12);
LV_FONT_DECLARE(font_doto_14);
LV_FONT_DECLARE(font_doto_18);
LV_FONT_DECLARE(font_doto_24);
LV_FONT_DECLARE(font_doto_32);
LV_FONT_DECLARE(font_doto_36);
LV_FONT_DECLARE(font_doto_48);

// Look up a custom font by family + size. Returns nullptr if not found.
// Falls back to nearest available size within the family.
const lv_font_t* pad_custom_font_lookup(uint8_t family, uint8_t size);

#endif // HAS_CUSTOM_FONTS
