#include "delay_action.cpp"
#include "back_action.cpp"
#include "volume_action.cpp"
#include "brightness_action.cpp"
#include "system_action.cpp"
#include "music_action.cpp"
#include "screen_action.cpp"
#include "key_action.cpp"
#include "ble_pair_action.cpp"
#include "cycle_pad_action.cpp"
#include "mqtt_action.cpp"
#include "ha_service_action.cpp"
#include "sound_alert_action.cpp"
#include "notify_action.cpp"
#include "visual_alert_action.cpp"
#include "timer_action.cpp"
#if HAS_IMAGE_LIBRARY
#include "image_next_action.cpp"
#include "image_previous_action.cpp"
#endif
#if HAS_CAMERA
#include "camera_capture_action.cpp"
#endif
